AWSTemplateFormatVersion: "2010-09-09"
Resources:
  FrontendBucket:
    Type: "AWS::S3::Bucket"
    Properties:
      BucketName: "spendsage-frontend-bucket-us-east-1"
      AccessControl: PublicRead
      WebsiteConfiguration:
        IndexDocument: "index.html"
        ErrorDocument: "index.html"

  FrontendBucketPolicy:
    Type: "AWS::S3::BucketPolicy"
    Properties:
      Bucket: !Ref FrontendBucket
      PolicyDocument:
        Statement:
          - Effect: "Allow"
            Principal: "*"
            Action: "s3:GetObject"
            Resource: !Sub "arn:aws:s3:::${FrontendBucket}/*"

  FrontendCloudFrontDistribution:
    Type: "AWS::CloudFront::Distribution"
    Properties:
      DistributionConfig:
        Origins:
          - DomainName: !GetAtt FrontendBucket.DomainName
            Id: "S3FrontendOrigin"
            S3OriginConfig: {}
        Enabled: true
        DefaultCacheBehavior:
          TargetOriginId: "S3FrontendOrigin"
          ViewerProtocolPolicy: "redirect-to-https"
          AllowedMethods: ["GET", "HEAD"]
          CachedMethods: ["GET", "HEAD"]
          ForwardedValues:
            QueryString: false
            Cookies:
              Forward: "none"
        DefaultRootObject: "index.html"
        ViewerCertificate:
          CloudFrontDefaultCertificate: true

Outputs:
  S3BucketURL:
    Description: "URL of the S3 bucket hosting the frontend"
    Value: !GetAtt FrontendBucket.WebsiteURL

  CloudFrontURL:
    Description: "CloudFront Distribution URL"
    Value: !GetAtt FrontendCloudFrontDistribution.DomainName
