AWSTemplateFormatVersion: "2010-09-09"

Parameters:
  HostedZoneId:
    Type: String
    Description: The Route53 Hosted Zone ID for the domain

Resources:
  FrontendBucket:
    Type: "AWS::S3::Bucket"
    Properties:
      BucketName: "spendsage-frontend-bucket-us-east-1"
      PublicAccessBlockConfiguration:
        BlockPublicAcls: false
        BlockPublicPolicy: false
        IgnorePublicAcls: false
        RestrictPublicBuckets: false
      WebsiteConfiguration:
        IndexDocument: "index.html"
        ErrorDocument: "index.html"

  FrontendBucketPolicy:
    Type: "AWS::S3::BucketPolicy"
    Properties:
      Bucket: !Ref FrontendBucket
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal: "*"
            Action: "s3:GetObject"
            Resource: !Sub "arn:aws:s3:::${FrontendBucket}/*"

  FrontendCloudFrontDistribution:
    Type: "AWS::CloudFront::Distribution"
    Properties:
      DistributionConfig:
        Aliases:
          - spendsages.click
        Origins:
          - DomainName: !GetAtt FrontendBucket.DomainName
            Id: "S3FrontendOrigin"
            S3OriginConfig: {}
        Enabled: true
        DefaultCacheBehavior:
          TargetOriginId: "S3FrontendOrigin"
          ViewerProtocolPolicy: "redirect-to-https"
          AllowedMethods: ["GET", "HEAD"]
          CachedMethods: ["GET", "HEAD"]
          ForwardedValues:
            QueryString: false
            Cookies:
              Forward: "none"
        DefaultRootObject: "index.html"
        ViewerCertificate:
          AcmCertificateArn: !Ref Certificate
          SslSupportMethod: sni-only
          MinimumProtocolVersion: TLSv1.2_2021

  Certificate:
    Type: AWS::CertificateManager::Certificate
    Properties:
      DomainName: spendsages.click
      ValidationMethod: DNS
      DomainValidationOptions:
        - DomainName: spendsages.click
          HostedZoneId: !Ref HostedZoneId  # You'll need to add this parameter

  CloudFrontRecordSet:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !Ref HostedZoneId  # You'll need to add this parameter
      Name: spendsages.click
      Type: A
      AliasTarget:
        DNSName: !GetAtt FrontendCloudFrontDistribution.DomainName
        HostedZoneId: Z2FDTNDATAQYW2  # This is CloudFront's hosted zone ID (constant)
        EvaluateTargetHealth: false

Outputs:
  S3BucketURL:
    Description: "URL of the S3 bucket hosting the frontend"
    Value: !GetAtt FrontendBucket.WebsiteURL

  CloudFrontURL:
    Description: "CloudFront Distribution URL"
    Value: !GetAtt FrontendCloudFrontDistribution.DomainName
