AWSTemplateFormatVersion: "2010-09-09"
Resources:
  BackendECRRepository:
    Type: "AWS::ECR::Repository"
    Properties:
      RepositoryName: "spendsage-backend"

  BackendInstanceRole:
    Type: "AWS::IAM::Role"
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              Service: "ec2.amazonaws.com"
            Action: "sts:AssumeRole"
      Policies:
        - PolicyName: "ECRPullPolicy"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: "Allow"
                Action:
                  - "ecr:GetDownloadUrlForLayer"
                  - "ecr:BatchGetImage"
                  - "ecr:BatchCheckLayerAvailability"
                  - "ecr:GetAuthorizationToken"
                Resource: "*"

  BackendInstanceProfile:
    Type: "AWS::IAM::InstanceProfile"
    Properties:
      Roles:
        - !Ref BackendInstanceRole

  BackendSecurityGroup:
    Type: "AWS::EC2::SecurityGroup"
    Properties:
      GroupDescription: "Allow HTTP traffic on port 3000"
      SecurityGroupIngress:
        - IpProtocol: "tcp"
          FromPort: 3000
          ToPort: 3000
          CidrIp: "0.0.0.0/0"

  BackendEC2Instance:
    Type: "AWS::EC2::Instance"
    Properties:
      InstanceType: "t3.micro"  # Smallest/cheapest EC2 instance
      ImageId: "ami-0c55b159cbfafe1f0"  # Amazon Linux 2 AMI (region-dependent)
      IamInstanceProfile: !Ref BackendInstanceProfile
      SecurityGroupIds:
        - !Ref BackendSecurityGroup
      UserData:
        Fn::Base64: |
          #!/bin/bash
          yum update -y
          yum install -y docker
          service docker start
          usermod -a -G docker ec2-user
          # Authenticate Docker to use ECR
          $(aws ecr get-login --no-include-email --region us-east-1)
          docker pull 216989142399.dkr.ecr.us-east-1.amazonaws.com/spendsage-backend:latest
          docker run -d -p 3000:3000 216989142399.dkr.ecr.us-east-1.amazonaws.com/spendsage-backend:latest
Outputs:
  InstanceId:
    Description: "Instance ID of the backend EC2 instance"
    Value: !Ref BackendEC2Instance
  EC2PublicIP:
    Description: "Public IP address of the EC2 instance"
    Value: !GetAtt BackendEC2Instance.PublicIp
